### PR TITLE
Update Anomalo <> Datahub DAG to Properly Distinguish Data Sources

### PR DESCRIPTION
**Pull request by njfritter**

### CODE REVIEW

**Comment by njfritter** [comment]
Anomalo check results continue to come in for the BigQuery datasets:
Screenshot 2024-04-09 at 3 00 21 PM
Screenshot 2024-04-09 at 3 00 41 PM

Anomalo check results are now showing up for the Snowflake datasets:
Screenshot 2024-04-09 at 3 01 22 PM
Screenshot 2024-04-09 at 3 01 43 PM

**Comment by njfritter** [comment]
One last edit: need to add the sensor task for the Snowflake cocktails table. Will have the DAG run tomorrow morning to confirm.

cc: @sorenarchibald

**Review by sorenarchibald — APPROVED** [review]
You've tested this?

**Comment by njfritter** [comment]
> You've tested this?

Yes, it ran successfully yesterday (see below); I also added screenshots of Datahub results above.

Screenshot 2024-04-10 at 10 48 57 AM

There will be another run in ~10 minutes; assuming it passes, I will be okay with merging this.

**Comment by njfritter** [comment]
@sorenarchibald Okay so there may be a few additional things this PR needs:
- The sensor tasks just hang if the selected Anomalo checks are NOT triggered on a schedule (i.e. triggered manually)

I will look into this.

**Comment by njfritter** [comment]
Most recent commit https://github.com/Qbizinc/sandbox-data-pipeline/pull/29/commits/6834c25503f24bbf6c8a95158445fc7bd4d89044 is able to get the results of the latest set of Anomalo checks (regardless of whether the checks were scheduled or manual).

The changes already ran successfully for today's DAGRun.

Will let this run through the weekend and check back on Monday.

Screenshot 2024-04-12 at 4 30 37 PM

**Comment by njfritter** [comment]
DAG ran successfully throughout the weekend.

Going to test one more thing:
- Will trigger a manual set of checks for one BigQuery and one Snowflake dataset
- Will rerun the Anomalo <> Datahub DAG and confirm that the **manual** checks were picked up by the DAG

Will post results afterwards

**Comment by njfritter** [comment]
DAG successfully picked up results of manually triggered run:

## BigQuery Weather Table
Screenshot 2024-04-15 at 2 10 41 PM
Screenshot 2024-04-15 at 2 10 55 PM
Screenshot 2024-04-15 at 2 12 05 PM
Screenshot 2024-04-15 at 2 12 13 PM

## Snowflake Cocktails Table
Screenshot 2024-04-15 at 2 11 06 PM
Screenshot 2024-04-15 at 2 11 15 PM
Screenshot 2024-04-15 at 2 17 26 PM
Screenshot 2024-04-15 at 2 16 25 PM


Considering this done. Merging then closing.

**Pull request merged**
